namespace: default
commonLabels:
  saas/common: "true"
  saas/service: tenant-registraion
resources:
- service.yaml
patchesJson6902:
- path: host-patch.yaml
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: tenant-registration-service-ingress
images:
- name: KUSTOMIZE_IMAGE
